@baseUrl = http://localhost:3000

### Setup: register a user for password tests
# @name setupPasswordUser
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "pw_{{$random(10000, 99999)}}",
  "password": "TestPass123!"
}

>>>
expect status 200
<<<

>>>capture
pwCookie from header Set-Cookie
<<<

### Password: new password too short
# @name passwordTooShort
# @depends setupPasswordUser
PUT {{baseUrl}}/api/player/password
Content-Type: application/json
Cookie: {{pwCookie}}

{
  "currentPassword": "TestPass123!",
  "newPassword": "short"
}

>>>
expect status 400
expect body.message contains "at least 8 characters"
<<<

### Password: missing new password
# @name passwordMissing
# @depends setupPasswordUser
PUT {{baseUrl}}/api/player/password
Content-Type: application/json
Cookie: {{pwCookie}}

{
  "currentPassword": "TestPass123!"
}

>>>
expect status 400
expect body.message contains "at least 8 characters"
<<<

### Password: missing current password
# @name passwordMissingCurrent
# @depends setupPasswordUser
PUT {{baseUrl}}/api/player/password
Content-Type: application/json
Cookie: {{pwCookie}}

{
  "newPassword": "NewPassword456!"
}

>>>
expect status 400
expect body.message contains "Current password is required"
<<<

### Password: wrong current password
# @name passwordWrongCurrent
# @depends setupPasswordUser
PUT {{baseUrl}}/api/player/password
Content-Type: application/json
Cookie: {{pwCookie}}

{
  "currentPassword": "WrongPassword99!",
  "newPassword": "NewPassword456!"
}

>>>
expect status 401
expect body.message contains "incorrect"
<<<

### Password: successful change
# @name passwordChangeSuccess
# @depends setupPasswordUser
PUT {{baseUrl}}/api/player/password
Content-Type: application/json
Cookie: {{pwCookie}}

{
  "currentPassword": "TestPass123!",
  "newPassword": "NewPassword456!"
}

>>>
expect status 200
expect body.success == true
<<<
