import type { Zone } from '../types/map'
import type { TeamId } from '../types/game'

export const ZONES: readonly Zone[] = [
  // ── Rookery (CHAFF base) ───────────────────────────────────────────────
  {
    id: 'rookery-terminal',
    name: 'Rookery Terminal',
    type: 'base',
    adjacentTo: ['rookery-anchor', 'seawall-t3-chaff', 'coldstore-t3-chaff', 'shallows-t3-chaff'],
    team: 'chaff',
    ice: false,
    // Bases sell too, not just fountains: shopping used to cost a detour to the
    // fountain and back — ~9 near-inputless ticks for one 430g purchase — and
    // both /learn and the client's own "return to base" error already told
    // players the base was a shop.
    shop: true,
  },
  {
    id: 'rookery-anchor',
    name: 'Rookery Anchor',
    type: 'anchor',
    adjacentTo: ['rookery-terminal'],
    team: 'chaff',
    ice: false,
    shop: true,
  },

  // ── Landing (AUDIT base) ──────────────────────────────────────────────────
  {
    id: 'landing-terminal',
    name: 'Landing Terminal',
    type: 'base',
    adjacentTo: ['landing-anchor', 'seawall-t3-audit', 'coldstore-t3-audit', 'shallows-t3-audit'],
    team: 'audit',
    ice: false,
    shop: true,
  },
  {
    id: 'landing-anchor',
    name: 'Landing Anchor',
    type: 'anchor',
    adjacentTo: ['landing-terminal'],
    team: 'audit',
    ice: false,
    shop: true,
  },

  // ── Top Lane (Chaff side → Audit side) ────────────────────────
  {
    id: 'seawall-t3-chaff',
    name: 'Seawall T3 (CHAFF)',
    type: 'route',
    adjacentTo: ['rookery-terminal', 'seawall-t2-chaff'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'seawall',
  },
  {
    id: 'seawall-t2-chaff',
    name: 'Seawall T2 (CHAFF)',
    type: 'route',
    adjacentTo: ['seawall-t3-chaff', 'seawall-t1-chaff', 'silt-chaff-upper'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'seawall',
  },
  {
    id: 'seawall-t1-chaff',
    name: 'Seawall T1 (CHAFF)',
    type: 'route',
    adjacentTo: ['seawall-t2-chaff', 'seawall-cross', 'silt-chaff-upper'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'seawall',
  },
  {
    id: 'seawall-cross',
    name: 'Seawall Crossing',
    type: 'cross',
    adjacentTo: ['seawall-t1-chaff', 'seawall-t1-audit', 'cache-seawall'],
    team: 'neutral',
    ice: false,
    shop: false,
    lane: 'seawall',
  },
  {
    id: 'seawall-t1-audit',
    name: 'Seawall T1 (AUDIT)',
    type: 'route',
    adjacentTo: ['seawall-cross', 'seawall-t2-audit', 'silt-audit-upper'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'seawall',
  },
  {
    id: 'seawall-t2-audit',
    name: 'Seawall T2 (AUDIT)',
    type: 'route',
    adjacentTo: ['seawall-t1-audit', 'seawall-t3-audit', 'silt-audit-upper'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'seawall',
  },
  {
    id: 'seawall-t3-audit',
    name: 'Seawall T3 (AUDIT)',
    type: 'route',
    adjacentTo: ['seawall-t2-audit', 'landing-terminal'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'seawall',
  },

  // ── Mid Lane (Chaff side → Audit side) ────────────────────────
  {
    id: 'coldstore-t3-chaff',
    name: 'Coldstore T3 (CHAFF)',
    type: 'route',
    adjacentTo: ['rookery-terminal', 'coldstore-t2-chaff'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-t2-chaff',
    name: 'Coldstore T2 (CHAFF)',
    type: 'route',
    adjacentTo: [
      'coldstore-t3-chaff',
      'coldstore-t1-chaff',
      'silt-chaff-upper',
      'silt-chaff-lower',
    ],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-t1-chaff',
    name: 'Coldstore T1 (CHAFF)',
    type: 'route',
    adjacentTo: ['coldstore-t2-chaff', 'coldstore-cross'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-cross',
    name: 'Coldstore Crossing',
    type: 'cross',
    adjacentTo: ['coldstore-t1-chaff', 'coldstore-t1-audit', 'cache-seawall', 'cache-shallows'],
    team: 'neutral',
    ice: false,
    shop: false,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-t1-audit',
    name: 'Coldstore T1 (AUDIT)',
    type: 'route',
    adjacentTo: ['coldstore-cross', 'coldstore-t2-audit'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-t2-audit',
    name: 'Coldstore T2 (AUDIT)',
    type: 'route',
    adjacentTo: [
      'coldstore-t1-audit',
      'coldstore-t3-audit',
      'silt-audit-upper',
      'silt-audit-lower',
    ],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'coldstore',
  },
  {
    id: 'coldstore-t3-audit',
    name: 'Coldstore T3 (AUDIT)',
    type: 'route',
    adjacentTo: ['coldstore-t2-audit', 'landing-terminal'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'coldstore',
  },

  // ── Bot Lane (Chaff side → Audit side) ────────────────────────
  {
    id: 'shallows-t3-chaff',
    name: 'Shallows T3 (CHAFF)',
    type: 'route',
    adjacentTo: ['rookery-terminal', 'shallows-t2-chaff'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'shallows',
  },
  {
    id: 'shallows-t2-chaff',
    name: 'Shallows T2 (CHAFF)',
    type: 'route',
    adjacentTo: ['shallows-t3-chaff', 'shallows-t1-chaff', 'silt-chaff-lower'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'shallows',
  },
  {
    id: 'shallows-t1-chaff',
    name: 'Shallows T1 (CHAFF)',
    type: 'route',
    adjacentTo: ['shallows-t2-chaff', 'shallows-cross', 'silt-chaff-lower'],
    team: 'chaff',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'shallows',
  },
  {
    id: 'shallows-cross',
    name: 'Shallows Crossing',
    type: 'cross',
    adjacentTo: ['shallows-t1-chaff', 'shallows-t1-audit', 'cache-shallows'],
    team: 'neutral',
    ice: false,
    shop: false,
    lane: 'shallows',
  },
  {
    id: 'shallows-t1-audit',
    name: 'Shallows T1 (AUDIT)',
    type: 'route',
    adjacentTo: ['shallows-cross', 'shallows-t2-audit', 'silt-audit-lower'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 1,
    lane: 'shallows',
  },
  {
    id: 'shallows-t2-audit',
    name: 'Shallows T2 (AUDIT)',
    type: 'route',
    adjacentTo: ['shallows-t1-audit', 'shallows-t3-audit', 'silt-audit-lower'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 2,
    lane: 'shallows',
  },
  {
    id: 'shallows-t3-audit',
    name: 'Shallows T3 (AUDIT)',
    type: 'route',
    adjacentTo: ['shallows-t2-audit', 'landing-terminal'],
    team: 'audit',
    ice: true,
    shop: false,
    tier: 3,
    lane: 'shallows',
  },

  // ── Jungle ─────────────────────────────────────────────────────
  {
    id: 'silt-chaff-upper',
    name: 'Chaff Upper Silt',
    type: 'silt',
    adjacentTo: ['seawall-t2-chaff', 'seawall-t1-chaff', 'coldstore-t2-chaff', 'cache-seawall'],
    team: 'chaff',
    ice: false,
    shop: false,
  },
  {
    id: 'silt-chaff-lower',
    name: 'Chaff Lower Silt',
    type: 'silt',
    adjacentTo: ['shallows-t2-chaff', 'shallows-t1-chaff', 'coldstore-t2-chaff', 'cache-shallows'],
    team: 'chaff',
    ice: false,
    shop: false,
  },
  {
    id: 'silt-audit-upper',
    name: 'Audit Upper Silt',
    type: 'silt',
    adjacentTo: ['seawall-t1-audit', 'seawall-t2-audit', 'coldstore-t2-audit', 'cache-seawall'],
    team: 'audit',
    ice: false,
    shop: false,
  },
  {
    id: 'silt-audit-lower',
    name: 'Audit Lower Silt',
    type: 'silt',
    adjacentTo: ['shallows-t1-audit', 'shallows-t2-audit', 'coldstore-t2-audit', 'cache-shallows'],
    team: 'audit',
    ice: false,
    shop: false,
  },

  // ── River Objectives ───────────────────────────────────────────
  {
    id: 'cache-seawall',
    name: 'Seawall Cache Drop',
    type: 'cross',
    adjacentTo: [
      'seawall-cross',
      'coldstore-cross',
      'silt-chaff-upper',
      'silt-audit-upper',
      'hollow',
    ],
    team: 'neutral',
    ice: false,
    shop: false,
  },
  {
    id: 'cache-shallows',
    name: 'Shallows Cache Drop',
    type: 'cross',
    adjacentTo: ['shallows-cross', 'coldstore-cross', 'silt-chaff-lower', 'silt-audit-lower'],
    team: 'neutral',
    ice: false,
    shop: false,
  },
  {
    id: 'hollow',
    name: 'The Hollow',
    type: 'objective',
    adjacentTo: ['cache-seawall'],
    team: 'neutral',
    ice: false,
    shop: false,
  },
] as const

export const ZONE_MAP: Record<string, Zone> = Object.fromEntries(ZONES.map((z) => [z.id, z]))

export const ZONE_IDS = ZONES.map((z) => z.id)

/**
 * Can THIS team shop in this zone?
 *
 * Both bases became shops so a 430g purchase no longer costs ~9 near-inputless
 * ticks — but `shop` alone is not the rule. Every shop zone is team-owned, and a
 * base is the natural place a breach happens, so a bare `zone.shop` test let an
 * attacker restock from the defender's shop mid-fight.
 */
export function isShopZoneFor(zoneId: string, team: TeamId): boolean {
  const zone = ZONE_MAP[zoneId]
  return !!zone?.shop && zone.team === team
}
