import type { Zone } from '../types/map'
import type { TeamId } from '../types/game'

export const ZONES: readonly Zone[] = [
  // ── Rookery (CHAFF base) ───────────────────────────────────────────────
  {
    id: 'radiant-base',
    name: 'Rookery Terminal',
    type: 'base',
    adjacentTo: ['radiant-fountain', 'top-t3-rad', 'mid-t3-rad', 'bot-t3-rad'],
    team: 'radiant',
    tower: false,
    // Bases sell too, not just fountains: shopping used to cost a detour to the
    // fountain and back — ~9 near-inputless ticks for one 430g purchase — and
    // both /learn and the client's own "return to base" error already told
    // players the base was a shop.
    shop: true,
  },
  {
    id: 'radiant-fountain',
    name: 'Rookery Anchor',
    type: 'fountain',
    adjacentTo: ['radiant-base'],
    team: 'radiant',
    tower: false,
    shop: true,
  },

  // ── Landing (AUDIT base) ──────────────────────────────────────────────────
  {
    id: 'dire-base',
    name: 'Landing Terminal',
    type: 'base',
    adjacentTo: ['dire-fountain', 'top-t3-dire', 'mid-t3-dire', 'bot-t3-dire'],
    team: 'dire',
    tower: false,
    shop: true,
  },
  {
    id: 'dire-fountain',
    name: 'Landing Anchor',
    type: 'fountain',
    adjacentTo: ['dire-base'],
    team: 'dire',
    tower: false,
    shop: true,
  },

  // ── Top Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'top-t3-rad',
    name: 'Seawall T3 (CHAFF)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'top-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'top',
  },
  {
    id: 'top-t2-rad',
    name: 'Seawall T2 (CHAFF)',
    type: 'lane',
    adjacentTo: ['top-t3-rad', 'top-t1-rad', 'jungle-rad-top'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'top',
  },
  {
    id: 'top-t1-rad',
    name: 'Seawall T1 (CHAFF)',
    type: 'lane',
    adjacentTo: ['top-t2-rad', 'top-river', 'jungle-rad-top'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'top',
  },
  {
    id: 'top-river',
    name: 'Seawall Crossing',
    type: 'river',
    adjacentTo: ['top-t1-rad', 'top-t1-dire', 'rune-top'],
    team: 'neutral',
    tower: false,
    shop: false,
    lane: 'top',
  },
  {
    id: 'top-t1-dire',
    name: 'Seawall T1 (AUDIT)',
    type: 'lane',
    adjacentTo: ['top-river', 'top-t2-dire', 'jungle-dire-top'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'top',
  },
  {
    id: 'top-t2-dire',
    name: 'Seawall T2 (AUDIT)',
    type: 'lane',
    adjacentTo: ['top-t1-dire', 'top-t3-dire', 'jungle-dire-top'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'top',
  },
  {
    id: 'top-t3-dire',
    name: 'Seawall T3 (AUDIT)',
    type: 'lane',
    adjacentTo: ['top-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'top',
  },

  // ── Mid Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'mid-t3-rad',
    name: 'Coldstore T3 (CHAFF)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'mid-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'mid',
  },
  {
    id: 'mid-t2-rad',
    name: 'Coldstore T2 (CHAFF)',
    type: 'lane',
    adjacentTo: ['mid-t3-rad', 'mid-t1-rad', 'jungle-rad-top', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'mid',
  },
  {
    id: 'mid-t1-rad',
    name: 'Coldstore T1 (CHAFF)',
    type: 'lane',
    adjacentTo: ['mid-t2-rad', 'mid-river'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'mid',
  },
  {
    id: 'mid-river',
    name: 'Coldstore Crossing',
    type: 'river',
    adjacentTo: ['mid-t1-rad', 'mid-t1-dire', 'rune-top', 'rune-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
    lane: 'mid',
  },
  {
    id: 'mid-t1-dire',
    name: 'Coldstore T1 (AUDIT)',
    type: 'lane',
    adjacentTo: ['mid-river', 'mid-t2-dire'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'mid',
  },
  {
    id: 'mid-t2-dire',
    name: 'Coldstore T2 (AUDIT)',
    type: 'lane',
    adjacentTo: ['mid-t1-dire', 'mid-t3-dire', 'jungle-dire-top', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'mid',
  },
  {
    id: 'mid-t3-dire',
    name: 'Coldstore T3 (AUDIT)',
    type: 'lane',
    adjacentTo: ['mid-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'mid',
  },

  // ── Bot Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'bot-t3-rad',
    name: 'Shallows T3 (CHAFF)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'bot-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'bot',
  },
  {
    id: 'bot-t2-rad',
    name: 'Shallows T2 (CHAFF)',
    type: 'lane',
    adjacentTo: ['bot-t3-rad', 'bot-t1-rad', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'bot',
  },
  {
    id: 'bot-t1-rad',
    name: 'Shallows T1 (CHAFF)',
    type: 'lane',
    adjacentTo: ['bot-t2-rad', 'bot-river', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'bot',
  },
  {
    id: 'bot-river',
    name: 'Shallows Crossing',
    type: 'river',
    adjacentTo: ['bot-t1-rad', 'bot-t1-dire', 'rune-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
    lane: 'bot',
  },
  {
    id: 'bot-t1-dire',
    name: 'Shallows T1 (AUDIT)',
    type: 'lane',
    adjacentTo: ['bot-river', 'bot-t2-dire', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 1,
    lane: 'bot',
  },
  {
    id: 'bot-t2-dire',
    name: 'Shallows T2 (AUDIT)',
    type: 'lane',
    adjacentTo: ['bot-t1-dire', 'bot-t3-dire', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 2,
    lane: 'bot',
  },
  {
    id: 'bot-t3-dire',
    name: 'Shallows T3 (AUDIT)',
    type: 'lane',
    adjacentTo: ['bot-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
    tier: 3,
    lane: 'bot',
  },

  // ── Jungle ─────────────────────────────────────────────────────
  {
    id: 'jungle-rad-top',
    name: 'Chaff Upper Silt',
    type: 'jungle',
    adjacentTo: ['top-t2-rad', 'top-t1-rad', 'mid-t2-rad', 'rune-top'],
    team: 'radiant',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-rad-bot',
    name: 'Chaff Lower Silt',
    type: 'jungle',
    adjacentTo: ['bot-t2-rad', 'bot-t1-rad', 'mid-t2-rad', 'rune-bot'],
    team: 'radiant',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-dire-top',
    name: 'Audit Upper Silt',
    type: 'jungle',
    adjacentTo: ['top-t1-dire', 'top-t2-dire', 'mid-t2-dire', 'rune-top'],
    team: 'dire',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-dire-bot',
    name: 'Audit Lower Silt',
    type: 'jungle',
    adjacentTo: ['bot-t1-dire', 'bot-t2-dire', 'mid-t2-dire', 'rune-bot'],
    team: 'dire',
    tower: false,
    shop: false,
  },

  // ── River Objectives ───────────────────────────────────────────
  {
    id: 'rune-top',
    name: 'Seawall Cache Drop',
    type: 'river',
    adjacentTo: ['top-river', 'mid-river', 'jungle-rad-top', 'jungle-dire-top', 'roshan-pit'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'rune-bot',
    name: 'Shallows Cache Drop',
    type: 'river',
    adjacentTo: ['bot-river', 'mid-river', 'jungle-rad-bot', 'jungle-dire-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'roshan-pit',
    name: 'The Hollow',
    type: 'objective',
    adjacentTo: ['rune-top'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
] as const

export const ZONE_MAP: Record<string, Zone> = Object.fromEntries(ZONES.map((z) => [z.id, z]))

export const ZONE_IDS = ZONES.map((z) => z.id)

/**
 * Can THIS team shop in this zone?
 *
 * Both bases became shops so a 430g purchase no longer costs ~9 near-inputless
 * ticks — but `shop` alone is not the rule. Every shop zone is team-owned, and a
 * base is the natural place a siege happens, so a bare `zone.shop` test let an
 * attacker restock from the defender's shop mid-fight.
 */
export function isShopZoneFor(zoneId: string, team: TeamId): boolean {
  const zone = ZONE_MAP[zoneId]
  return !!zone?.shop && zone.team === team
}
