import type { Zone } from '../types/map'

export const ZONES: readonly Zone[] = [
  // ── Radiant Base ───────────────────────────────────────────────
  {
    id: 'radiant-base',
    name: 'Radiant Base',
    type: 'base',
    adjacentTo: ['radiant-fountain', 'top-t3-rad', 'mid-t3-rad', 'bot-t3-rad'],
    team: 'radiant',
    tower: false,
    shop: false,
  },
  {
    id: 'radiant-fountain',
    name: 'Radiant Fountain',
    type: 'fountain',
    adjacentTo: ['radiant-base'],
    team: 'radiant',
    tower: false,
    shop: true,
  },

  // ── Dire Base ──────────────────────────────────────────────────
  {
    id: 'dire-base',
    name: 'Dire Base',
    type: 'base',
    adjacentTo: ['dire-fountain', 'top-t3-dire', 'mid-t3-dire', 'bot-t3-dire'],
    team: 'dire',
    tower: false,
    shop: false,
  },
  {
    id: 'dire-fountain',
    name: 'Dire Fountain',
    type: 'fountain',
    adjacentTo: ['dire-base'],
    team: 'dire',
    tower: false,
    shop: true,
  },

  // ── Top Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'top-t3-rad',
    name: 'Top Lane T3 (Radiant)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'top-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'top-t2-rad',
    name: 'Top Lane T2 (Radiant)',
    type: 'lane',
    adjacentTo: ['top-t3-rad', 'top-t1-rad', 'jungle-rad-top'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'top-t1-rad',
    name: 'Top Lane T1 (Radiant)',
    type: 'lane',
    adjacentTo: ['top-t2-rad', 'top-river', 'jungle-rad-top'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'top-river',
    name: 'Top River Crossing',
    type: 'river',
    adjacentTo: ['top-t1-rad', 'top-t1-dire', 'rune-top'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'top-t1-dire',
    name: 'Top Lane T1 (Dire)',
    type: 'lane',
    adjacentTo: ['top-river', 'top-t2-dire', 'jungle-dire-top'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'top-t2-dire',
    name: 'Top Lane T2 (Dire)',
    type: 'lane',
    adjacentTo: ['top-t1-dire', 'top-t3-dire', 'jungle-dire-top'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'top-t3-dire',
    name: 'Top Lane T3 (Dire)',
    type: 'lane',
    adjacentTo: ['top-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
  },

  // ── Mid Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'mid-t3-rad',
    name: 'Mid Lane T3 (Radiant)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'mid-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'mid-t2-rad',
    name: 'Mid Lane T2 (Radiant)',
    type: 'lane',
    adjacentTo: ['mid-t3-rad', 'mid-t1-rad', 'jungle-rad-top', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'mid-t1-rad',
    name: 'Mid Lane T1 (Radiant)',
    type: 'lane',
    adjacentTo: ['mid-t2-rad', 'mid-river'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'mid-river',
    name: 'Mid River Crossing',
    type: 'river',
    adjacentTo: ['mid-t1-rad', 'mid-t1-dire', 'rune-top', 'rune-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'mid-t1-dire',
    name: 'Mid Lane T1 (Dire)',
    type: 'lane',
    adjacentTo: ['mid-river', 'mid-t2-dire'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'mid-t2-dire',
    name: 'Mid Lane T2 (Dire)',
    type: 'lane',
    adjacentTo: ['mid-t1-dire', 'mid-t3-dire', 'jungle-dire-top', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'mid-t3-dire',
    name: 'Mid Lane T3 (Dire)',
    type: 'lane',
    adjacentTo: ['mid-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
  },

  // ── Bot Lane (Radiant side → Dire side) ────────────────────────
  {
    id: 'bot-t3-rad',
    name: 'Bot Lane T3 (Radiant)',
    type: 'lane',
    adjacentTo: ['radiant-base', 'bot-t2-rad'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'bot-t2-rad',
    name: 'Bot Lane T2 (Radiant)',
    type: 'lane',
    adjacentTo: ['bot-t3-rad', 'bot-t1-rad', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'bot-t1-rad',
    name: 'Bot Lane T1 (Radiant)',
    type: 'lane',
    adjacentTo: ['bot-t2-rad', 'bot-river', 'jungle-rad-bot'],
    team: 'radiant',
    tower: true,
    shop: false,
  },
  {
    id: 'bot-river',
    name: 'Bot River Crossing',
    type: 'river',
    adjacentTo: ['bot-t1-rad', 'bot-t1-dire', 'rune-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'bot-t1-dire',
    name: 'Bot Lane T1 (Dire)',
    type: 'lane',
    adjacentTo: ['bot-river', 'bot-t2-dire', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'bot-t2-dire',
    name: 'Bot Lane T2 (Dire)',
    type: 'lane',
    adjacentTo: ['bot-t1-dire', 'bot-t3-dire', 'jungle-dire-bot'],
    team: 'dire',
    tower: true,
    shop: false,
  },
  {
    id: 'bot-t3-dire',
    name: 'Bot Lane T3 (Dire)',
    type: 'lane',
    adjacentTo: ['bot-t2-dire', 'dire-base'],
    team: 'dire',
    tower: true,
    shop: false,
  },

  // ── Jungle ─────────────────────────────────────────────────────
  {
    id: 'jungle-rad-top',
    name: 'Radiant Top Jungle',
    type: 'jungle',
    adjacentTo: ['top-t2-rad', 'top-t1-rad', 'mid-t2-rad', 'rune-top'],
    team: 'radiant',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-rad-bot',
    name: 'Radiant Bot Jungle',
    type: 'jungle',
    adjacentTo: ['bot-t2-rad', 'bot-t1-rad', 'mid-t2-rad', 'rune-bot'],
    team: 'radiant',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-dire-top',
    name: 'Dire Top Jungle',
    type: 'jungle',
    adjacentTo: ['top-t1-dire', 'top-t2-dire', 'mid-t2-dire', 'rune-top'],
    team: 'dire',
    tower: false,
    shop: false,
  },
  {
    id: 'jungle-dire-bot',
    name: 'Dire Bot Jungle',
    type: 'jungle',
    adjacentTo: ['bot-t1-dire', 'bot-t2-dire', 'mid-t2-dire', 'rune-bot'],
    team: 'dire',
    tower: false,
    shop: false,
  },

  // ── River Objectives ───────────────────────────────────────────
  {
    id: 'rune-top',
    name: 'Top Rune Spot',
    type: 'river',
    adjacentTo: ['top-river', 'mid-river', 'jungle-rad-top', 'jungle-dire-top', 'roshan-pit'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'rune-bot',
    name: 'Bot Rune Spot',
    type: 'river',
    adjacentTo: ['bot-river', 'mid-river', 'jungle-rad-bot', 'jungle-dire-bot'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
  {
    id: 'roshan-pit',
    name: 'Roshan Pit',
    type: 'objective',
    adjacentTo: ['rune-top'],
    team: 'neutral',
    tower: false,
    shop: false,
  },
] as const

export const ZONE_MAP: Record<string, Zone> = Object.fromEntries(ZONES.map((z) => [z.id, z]))

export const ZONE_IDS = ZONES.map((z) => z.id)
